### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by KnowledgeGarden** [keikreutler/transformap#7]
The transformap.co says it is LGPL; the license posted here is GPL. Which?

**Comment by almereyda** [comment]
You are right, concerning a comparison of

* https://github.com/TransforMap/transformap.github.io/blob/b46689870e8dada27f1c6e22696568074877b1c6/src/layouts/default.html.eco#L90 and
* https://github.com/TransforMap/transformap.github.io/commit/fc0627602ac3fba361fe564ecf462f96fff63102

there is a contradiction between the two.
I suppose it's best to fix it over there, thus closing.

**Comment by almereyda** [comment]
@keikreutler Let me suggest to disable issues in this repository, get some proper documentation in the README over there, pull back and all set.

**Comment by keikreutler** [comment]
This is no longer a working repository. It was the stub of
transformap.github.io. I'd prefer to simply delete this repo.

**Comment by almereyda** [comment]
Yes, it lives in your namespace and as such is subject to your
consideration.

I agree we don't need it anymore.
